#!/bin/bash

sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si
cd ..
rm -rf yay-bin

yay -S ttf-jetbrains-mono-nerd ttf-font-awesome noto-fonts ttf-dejavu --noconfirm

# some cloudflare warp stuff
yay -S cloudflare-warp-bin --noconfirm
sudo systemctl enable warp-svc --now
warp-cli registration new && warp-cli connect
